[project]
name = "karma-medeval"
version = "0.1.9"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "accelerate>=1.7.0",
    "boto3>=1.35.0",
    "click>=8.0.0",
    "datasets>=3.6.0",
    "duckdb>=0.9.0",
    "evaluate>=0.4.0",
    "mysql-connector-python>=9.3.0",
    "pillow>=11.1.0",
    "python-dotenv>=1.1.0",
    "rich>=13.0.0",
    "scikit-learn>=1.3.0",
    "torch>=2.7.1",
    "tqdm>=4.64.0",
    "transformers==4.53.0",
    "weave>=0.50.0",
    "numpy>=2.2.6",
    "onnxruntime>=1.22.0",
    "google-genai>=1.24.0",
    "openai>=1.93.0",
    "requests>=2.32.4",
    "simple-term-menu>=1.6.6",
    "ipython>=8.37.0",
    "pandas>=2.0.0",
    "audiomentations>=0.33.0",
    "soundfile>=0.12.1",
]

[project.urls]
Repository = "https://github.com/eka-care/KARMA-OpenMedEvalKit"
Documentation = "https://karma.eka.care"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
karma = "karma.cli.main:main"


[tool.setuptools.package-data]
karma = [
    "processors/glm/*",
]


[project.optional-dependencies]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.0",
    "ipywidgets>=8.1.7",
    "line-profiler>=4.2.0",
]

audio = [
    "elevenlabs>=2.5.0",
    "indic-nlp-library>=0.92",
    "langdetect>=1.0.9",
    "indic-transliteration>=2.0.0",
    "editdistance>=0.8.1",
    "google-transliteration-api>=1.0.3",
    "jiwer>=4.0.0",
    "torchaudio>=2.7.1",
    "librosa>=0.11.0",
    "num2words>=0.5.14",
]

# This enables pip install karma[all]
all = [
    "karma-medeval[dev,audio]",
]
